### ISSUE TITLE
Where's v0.1.8?

### ISSUE THREAD

**Issue by azahid** [edgeware/python-circuit#12]
pip install python-circuit
   Downloading/unpacking python-circuit
   Downloading python-circuit-0.1.5.tar.gz

Looks like 0.1.8 is missing from
https://pypi.python.org/simple/python-circuit/

**Comment by renstrom** [comment]
Hi, unfortunately I'm currently on summer vacation. But will try to resolve this when I get back, the problem is that the python-circuit package on PyPi is owned by a former employee ("jrydberg"), so I will reach out to him to get him to transfer ownership (we had them same issue with https://pypi.python.org/pypi/structprop).

**Comment by renstrom** [comment]
I've added 0.1.7 and 0.1.8 to PyPi. I decided to cut a new release (0.1.9) as well with the latest changes from master.
